"""
Google Colab Export Template — Generated by mama
Run this notebook in Google Colab to train/fine-tune with your project config.

Instructions:
  1. Upload this file to Google Colab (File → Upload notebook)
  2. Upload your project folder or set the paths below
  3. Run all cells
"""

PROJECT_PATH = "/content/project"  # update to your project folder
OUTPUT_DIR = "/content/outputs"
MODEL_NAME = None   # set to override model, e.g. "bert-base-uncased"

# ── 1. Install Dependencies ──────────────────────────────────────────

import subprocess, sys, json, os, shutil
from pathlib import Path

def run(cmd):
    print(f"$ {cmd}")
    subprocess.check_call(cmd, shell=True)

run("pip install -q torch transformers datasets accelerate tensorboard")

# ── 2. Load Project Config ───────────────────────────────────────────

project_path = Path(PROJECT_PATH)
config_path = project_path / "training_config.json"

if not config_path.exists():
    # Fallback: look for project.json
    config_path = project_path / "project.json"

if config_path.exists():
    with open(config_path) as f:
        config = json.load(f)
    print(f"Loaded config from {config_path}")
else:
    config = {}
    print("No config found, using defaults")

model_name = MODEL_NAME or config.get("model_name_or_path", "bert-base-uncased")
output_dir = Path(OUTPUT_DIR)
output_dir.mkdir(parents=True, exist_ok=True)

# ── 3. Load Model & Tokenizer ────────────────────────────────────────

from transformers import AutoModelForSequenceClassification, AutoTokenizer

print(f"Loading model: {model_name}")
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=config.get("num_labels", 2)
)

# ── 4. Load Dataset ──────────────────────────────────────────────────

dataset_path = config.get("dataset_path", "")
if dataset_path and Path(dataset_path).exists():
    from datasets import load_from_disk
    dataset = load_from_disk(dataset_path)
    print(f"Loaded dataset from {dataset_path}")
else:
    print("No dataset found. Create a sample dataset for testing.")
    from datasets import Dataset
    dataset = Dataset.from_dict({
        "text": ["example positive", "example negative"],
        "label": [1, 0]
    })

def tokenize_function(examples):
    return tokenizer(examples["text"], padding="max_length", truncation=True)

tokenized_datasets = dataset.map(tokenize_function, batched=True)
if "train" in tokenized_datasets:
    train_dataset = tokenized_datasets["train"]
else:
    train_dataset = tokenized_datasets

# ── 5. Training ──────────────────────────────────────────────────────

from transformers import TrainingArguments, Trainer

training_args = TrainingArguments(
    output_dir=str(output_dir),
    evaluation_strategy="no",
    learning_rate=config.get("learning_rate", 2e-5),
    per_device_train_batch_size=config.get("batch_size", 8),
    num_train_epochs=config.get("num_epochs", 3),
    weight_decay=config.get("weight_decay", 0.01),
    save_steps=config.get("save_steps", 500),
    logging_dir=str(output_dir / "logs"),
    logging_steps=config.get("logging_steps", 10),
    report_to="tensorboard",
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
)

print("Starting training...")
trainer.train()

# ── 6. Save Model ────────────────────────────────────────────────────

trainer.save_model(str(output_dir / "final_model"))
tokenizer.save_pretrained(str(output_dir / "final_model"))
print(f"Model saved to {output_dir / 'final_model'}")
print("Done! Download your model from the Files panel on the left.")
