/**
 * JS Export Template — Generated by mama
 *
 * Load and run your exported model in the browser using ONNX Runtime Web.
 *
 * Usage:
 *   1. Place this file alongside your exported model (.onnx) and tokenizer
 *   2. Include ONNX Runtime Web in your HTML:
 *      <script src="https://cdn.jsdelivr.net/npm/onnxruntime-web/dist/ort.min.js"></script>
 *   3. Call ModelRunner.predict(text) to run inference
 */

class ModelRunner {
  constructor(modelPath = "./model.onnx") {
    this.modelPath = modelPath;
    this.session = null;
    this.initialized = false;
  }

  async init() {
    if (this.initialized) return;
    try {
      this.session = await ort.InferenceSession.create(this.modelPath);
      this.initialized = true;
      console.log("Model loaded successfully from", this.modelPath);
    } catch (err) {
      console.error("Failed to load model:", err);
      throw err;
    }
  }

  async predict(inputText) {
    if (!this.initialized) await this.init();

    // Tokenize input — replace with your tokenizer logic
    const inputIds = this._tokenize(inputText);
    const attentionMask = inputIds.map(() => 1);

    const feeds = {
      input_ids: new ort.Tensor("int64", inputIds, [1, inputIds.length]),
      attention_mask: new ort.Tensor("int64", attentionMask, [1, attentionMask.length]),
    };

    try {
      const results = await this.session.run(feeds);
      const logits = results.logits || results.output;
      return this._postprocess(logits);
    } catch (err) {
      console.error("Inference failed:", err);
      throw err;
    }
  }

  _tokenize(text) {
    // Simple whitespace tokenization — replace with full tokenizer
    const vocab = { "[CLS]": 101, "[SEP]": 102, "[PAD]": 0 };
    const tokens = text.toLowerCase().split(/\s+/);
    const ids = [vocab["[CLS]"]];
    for (const t of tokens) {
      ids.push(vocab[t] || 100);
    }
    ids.push(vocab["[SEP]"]);
    return Big64Array ? BigInt64Array.from(ids) : ids;
  }

  _postprocess(logits) {
    const data = logits.data || logits;
    const maxIdx = data.indexOf(Math.max(...data));
    return { class: maxIdx, scores: Array.from(data) };
  }

  destroy() {
    this.session = null;
    this.initialized = false;
  }
}

// ── HTML Integration Example (uncomment for standalone use) ──────────
//
// <!DOCTYPE html>
// <html>
// <head>
//   <title>Model Demo</title>
//   <script src="https://cdn.jsdelivr.net/npm/onnxruntime-web/dist/ort.min.js"></script>
// </head>
// <body>
//   <h1>Model Demo</h1>
//   <textarea id="inputText" rows="4" cols="50">Type something...</textarea>
//   <button id="predictBtn">Predict</button>
//   <pre id="output"></pre>
//
//   <script src="js_export.js"></script>
//   <script>
//     const runner = new ModelRunner("./model.onnx");
//     document.getElementById("predictBtn").onclick = async () => {
//       const text = document.getElementById("inputText").value;
//       const result = await runner.predict(text);
//       document.getElementById("output").textContent = JSON.stringify(result, null, 2);
//     };
//   </script>
// </body>
// </html>
