#!/usr/bin/env python3
"""
train_unsloth.py - Unsloth fine-tuning runner (the "fast" backend).

Target: CUDA (Linux) and MPS (Apple Silicon); CPU fallback is allowed but slow.

This backend is built around the standalone Unsloth script (the same file the
Export page writes to disk). Flow:

  1. validate the backend (CUDA / MPS + unsloth importable),
  2. make sure "unsloth" is installed (pip install, streamed like the
     built-in backend's install_deps step),
  3. render a standalone train_unsloth.py from the mama training config
     (the exact artifact the Export page produces), embedding CONFIG_JSON,
  4. spawn: python train_unsloth.py --config training_config.json
     and stream its output back to the mama IPC protocol:

       {"type": "metric", "step": N, "loss": X, "learning_rate": X, "epoch": X}
       {"type": "status", "message": "...", "stage": "loading|training|saving|done|error"}
       {"type": "progress", "current": N, "total": N, "stage": "..."}
       {"type": "error", "code": "OOM|CONFIG|IMPORT|TRAIN", "message": "...", "suggestions": [...]}

Pause / Resume / Cancel markers match the built-in backend: a ".pause" or
".cancel" file inside the output directory. Cancelling terminates the
python process tree; pausing uses SIGSTOP/SIGCONT on the process group.

Import mode (--mode import --script <script.py>): parses an existing Unsloth
training script (as exported by mama, or hand written) back into a mama
training_config.json so the run can be edited / resumed / re-exported.
"""

import sys
import os
import re
import json
import time
import signal
import argparse
import threading
import subprocess
from pathlib import Path

# ── Structured output ────────────────────────────────────────────────────────


def emit(obj: dict):
    print(json.dumps(obj), flush=True)


def emit_error(code, message, suggestions=None, traceback_str=None):
    emit({"type": "error", "code": code, "message": message,
          "suggestions": suggestions or [], "traceback": traceback_str})
    sys.exit(1)


def emit_status(message, stage="loading"):
    emit({"type": "status", "message": message, "stage": stage})


def emit_progress(current, total, stage=""):
    emit({"type": "progress", "current": current, "total": total, "stage": stage})


# ── Device / platform detection ──────────────────────────────────────────────


def get_device():
    try:
        import torch
    except ImportError:
        return "cpu"
    if torch.cuda.is_available():
        return "cuda"
    if hasattr(torch.backends, "mps") and torch.backends.mps.is_available():
        return "mps"
    return "cpu"


def is_unsloth_installed():
    try:
        import unsloth  # noqa: F401
        return True
    except ImportError:
        return False


# ── Standalone script rendering ──────────────────────────────────────────────
# The Export page writes this exact script to disk. The runner embeds the
# config JSON, so the file is fully self-contained when moved elsewhere.


def render_standalone_script(cfg: dict) -> str:
    """Build the standalone Unsloth script as a string from a mama config."""
    # Embed via a triple-quoted string so the file is isolated from the
    # surrounding code and a "--mode import" round-trip can recover it.
    escaped = json.dumps(cfg, indent=2).replace("'''", "\\'\\'\\'")
    return _STANDALONE_TEMPLATE.replace('@CONFIG_JSON@', "'''" + escaped + "'''")


_STANDALONE_TEMPLATE = '''#!/usr/bin/env python3
"""
train_unsloth.py - Standalone Unsloth fine-tuning script (generated by mama).

Run directly:
  python train_unsloth.py --config training_config.json

Or edit CONFIG_JSON below and just run:
  python train_unsloth.py
"""

import json
import os
import sys
from pathlib import Path

import torch

# ── CONFIG (embedded by mama; --config overrides it) ─────────────────────────
CONFIG_JSON = @CONFIG_JSON@


def load_cfg():
    arg_path = None
    if "--config" in sys.argv:
        arg_path = sys.argv[sys.argv.index("--config") + 1]
    if arg_path:
        with open(arg_path, "r", encoding="utf-8") as f:
            return json.load(f)
    return json.loads(CONFIG_JSON)


def pick_dtype(cfg, device):
    t = (cfg.get("torch_dtype") or "").lower()
    if t == "float16":
        return torch.float16
    if t == "bfloat16":
        return torch.bfloat16
    if t == "float32":
        return torch.float32
    if device == "cuda":
        return torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16
    return torch.float32


def format_dataset(dataset, tokenizer, cfg):
    """Normalize every supported dataset shape into a single 'text' column.

    - "messages" / "conversations" columns -> chat template
    - "prompt" + "completion" columns -> instruction template
    - otherwise use cfg["text_column"] (default "text") as-is
    """
    columns = set(dataset.column_names)

    if "messages" in columns or "conversations" in columns:
        chat_col = "messages" if "messages" in columns else "conversations"

        def _chat(examples):
            texts = []
            for msg in examples[chat_col]:
                texts.append(tokenizer.apply_chat_template(
                    msg, tokenize=False, add_generation_prompt=False))
            return {"text": texts}

        return dataset.map(_chat, batched=True, remove_columns=list(columns))

    if "prompt" in columns and "completion" in columns:
        def _pc(examples):
            texts = []
            for p, c in zip(examples["prompt"], examples["completion"]):
                texts.append(
                    "### Instruction\\n" + str(p) +
                    "\\n\\n### Response\\n" + str(c))
            return {"text": texts}
        return dataset.map(_pc, batched=True, remove_columns=list(columns))

    text_column = cfg.get("text_column") or "text"
    if text_column in columns:
        dataset = dataset.map(lambda x: {"text": x[text_column]}, batched=False)
        rest = [c for c in list(columns) if c != text_column]
        if rest:
            dataset = dataset.remove_columns(rest)
        return dataset

    raise ValueError(
        "dataset has no 'text'/'messages'/'prompt'+'completion' column. "
        "Available columns: " + ", ".join(sorted(columns)))


def main():
    try:
        import torch
        from unsloth import FastLanguageModel
        get_peft_model = FastLanguageModel.get_peft_model
    except ImportError as e:
        print("Missing dependency: " + str(e), file=sys.stderr)
        sys.exit(1)

    cfg = load_cfg()
    output_dir = cfg.get("output_dir") or "output"
    Path(output_dir).mkdir(parents=True, exist_ok=True)

    device = "cuda" if torch.cuda.is_available() else (
        "mps" if getattr(torch.backends, "mps", None)
        and torch.backends.mps.is_available() else "cpu")

    model_name = cfg.get("model_name_or_path")
    if not model_name:
        print("model_name_or_path is required", file=sys.stderr)
        sys.exit(1)

    max_seq_length = int(cfg.get("max_seq_length") or 2048)
    use_qlora = bool(cfg.get("use_qlora", False))
    dtype = pick_dtype(cfg, device)

    # ── Load model ─────────────────────────────────────────────────────────
    print("[loading] Loading " + model_name, flush=True)
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=model_name,
        max_seq_length=max_seq_length,
        dtype=dtype,
        load_in_8bit=False,
        load_in_4bit=use_qlora,
        trust_remote_code=bool(cfg.get("trust_remote_code", False)),
    )

    # ── PEFT ───────────────────────────────────────────────────────────────
    if cfg.get("use_lora", True):
        model = get_peft_model(
            model,
            r=int(cfg.get("lora_r", 8)),
            target_modules=cfg.get("lora_target_modules") or [
                "q_proj", "k_proj", "v_proj", "o_proj",
                "gate_proj", "up_proj", "down_proj",
            ],
            lora_alpha=int(cfg.get("lora_alpha", 16)),
            lora_dropout=float(cfg.get("lora_dropout", 0.05)),
            bias="none",
            use_gradient_checkpointing="trained" if not cfg.get("gradient_checkpointing", True) else "unsloth",
            random_state=int(cfg.get("seed", 42)),
            use_rslora=False,
            loftq_config=None,
        )

    # ── Dataset ────────────────────────────────────────────────────────────
    from datasets import load_dataset, load_from_disk

    dataset_path = cfg.get("dataset_path")
    if not dataset_path:
        print("dataset_path is required", file=sys.stderr)
        sys.exit(1)

    print("[loading] Loading dataset from " + dataset_path, flush=True)
    path_obj = Path(dataset_path)
    fmt = (cfg.get("dataset_format") or "").lower()
    try:
        if path_obj.exists():
            if fmt == "json" or path_obj.suffix == ".json":
                dataset = load_dataset("json", data_files=str(path_obj), split="train")
            elif fmt == "csv" or path_obj.suffix == ".csv":
                dataset = load_dataset("csv", data_files=str(path_obj), split="train")
            elif fmt == "parquet" or path_obj.suffix == ".parquet":
                dataset = load_dataset("parquet", data_files=str(path_obj), split="train")
            elif path_obj.is_dir():
                dataset = load_from_disk(str(path_obj))
            else:
                dataset = load_dataset(str(path_obj), split="train")
        else:
            dataset = load_dataset(dataset_path, split="train")
    except Exception as e:
        print("Failed to load dataset: " + str(e), file=sys.stderr)
        sys.exit(1)

    max_samples = cfg.get("max_samples")
    if max_samples and int(max_samples) < len(dataset):
        dataset = dataset.select(range(int(max_samples)))
        print("[*] Using subset of %d samples" % int(max_samples), flush=True)

    dataset = format_dataset(dataset, tokenizer, cfg)
    print("[*] Dataset ready: %d samples" % len(dataset), flush=True)

    # ── Train ──────────────────────────────────────────────────────────────
    from trl import SFTTrainer, SFTConfig

    training_args = SFTConfig(
        output_dir=output_dir,
        max_length=max_seq_length,
        per_device_train_batch_size=int(cfg.get("per_device_train_batch_size", 2)),
        gradient_accumulation_steps=int(cfg.get("gradient_accumulation_steps", 4)),
        learning_rate=float(cfg.get("learning_rate", 2e-4)),
        warmup_steps=int(cfg.get("warmup_steps", 100)),
        num_train_epochs=int(cfg.get("num_train_epochs", 3)),
        max_steps=int(cfg.get("max_steps", -1)),
        logging_steps=int(cfg.get("logging_steps", 10)),
        save_steps=int(cfg.get("save_steps", 500)),
        save_total_limit=int(cfg.get("save_total_limit", 3)),
        eval_strategy="no",
        save_strategy="steps",
        bf16=bool(cfg.get("bf16", device == "cuda")),
        fp16=bool(cfg.get("fp16", False)),
        gradient_checkpointing=bool(cfg.get("gradient_checkpointing", True)),
        optim=cfg.get("optim", "adamw_8bit"),
        lr_scheduler_type=cfg.get("lr_scheduler_type", "cosine"),
        weight_decay=float(cfg.get("weight_decay", 0.01)),
        max_grad_norm=float(cfg.get("max_grad_norm", 1.0)),
        seed=int(cfg.get("seed", 42)),
        dataloader_num_workers=int(cfg.get("dataloader_num_workers", 2)),
        report_to="none",
        ddp_find_unused_parameters=(not cfg.get("use_lora", True)) or None,
    )

    trainer = SFTTrainer(
        model=model,
        processing_class=tokenizer,
        train_dataset=dataset,
        args=training_args,
    )

    print("[*] Starting training on %s" % device, flush=True)
    trainer.train()

    # ── Save ───────────────────────────────────────────────────────────────
    print("[saving] Saving model...", flush=True)
    try:
        model.save_pretrained(output_dir)
        tokenizer.save_pretrained(output_dir)
    except Exception as e:
        print("Save (peft) failed: %s" % e, file=sys.stderr)

    try:
        if hasattr(model, "save_pretrained_merged"):
            model.save_pretrained_merged(output_dir, tokenizer, save_method="merged_16bit")
    except Exception as e:
        print("Merged save failed (adapter-only save kept): %s" % e, file=sys.stderr)

    cfg_path = os.path.join(output_dir, "training_config.json")
    with open(cfg_path, "w", encoding="utf-8") as f:
        json.dump(cfg, f, indent=2)

    print("Model saved successfully to " + output_dir, flush=True)


if __name__ == "__main__":
    main()
'''


# ── Script import parsing (Unsloth script -> mama config JSON) ────────────────

_NUM = r"[-+]?\d*\.?\d+(?:[eE][-+]?\d+)?"


def _parse_float(value):
    if value is None:
        return None
    try:
        return float(value.strip().rstrip(',').rstrip(')'))
    except (ValueError, AttributeError):
        return None


def _parse_int(value):
    f = _parse_float(value)
    return int(f) if f is not None else None


def parse_import_config(script_text: str) -> dict:
    """Best-effort extraction of a mama config from any Unsloth-style script."""
    cfg = {}

    # Embedded mama config — exact round-trip.
    m = re.search(r"CONFIG_JSON\s*=\s*(?:'''|\"\"\")([\s\S]*?)(?:'''|\"\"\")",
                  script_text)
    if m:
        try:
            embedded = json.loads(m.group(1))
            if isinstance(embedded, dict):
                return dict(embedded)
        except Exception:
            pass

    # model_name
    m = re.search(
        r'FastLanguageModel\.from_pretrained\s*\([^)]*?model_name\s*=\s*["\']([^"\']+)["\']',
        script_text)
    if not m:
        m = re.search(r'[Ff]rom_pretrained\s*\(\s*["\']([^"\']+)["\']', script_text)
    if m:
        cfg["model_name_or_path"] = m.group(1)
    else:
        m = re.search(r'\bmodel_name\s*=\s*["\']([^"\']+)["\']', script_text)
        if m:
            cfg["model_name_or_path"] = m.group(1)

    # qlora / lora
    cfg["use_qlora"] = bool(re.search(r"load_in_4bit\s*=\s*True", script_text))
    cfg.setdefault("use_lora", True)

    m = re.search(r'\bmax_seq_length\s*=\s*' + _NUM, script_text)
    if m:
        cfg["max_seq_length"] = _parse_int(m.group(0).split("=", 1)[1])

    m = re.search(r"\bget_peft_model\s*\([\s\S]{0,600}?\br\s*=\s*" + _NUM, script_text)
    if m:
        cfg["lora_r"] = _parse_int(m.group(0).split("r=")[-1].split(",")[0])
    for key in ("lora_alpha", "lora_dropout"):
        m = re.search(r"\b" + key + r"\s*=\s*" + _NUM, script_text)
        if m:
            cfg[key] = float(m.group(0).split("=", 1)[1].split(",")[0].strip())

    # SFTTrainer args
    arg_map = {
        "learning_rate": "learning_rate",
        "per_device_train_batch_size": "per_device_train_batch_size",
        "gradient_accumulation_steps": "gradient_accumulation_steps",
        "num_train_epochs": "num_train_epochs",
        "max_steps": "max_steps",
        "warmup_steps": "warmup_steps",
        "logging_steps": "logging_steps",
        "save_steps": "save_steps",
        "max_seq_length": "max_seq_length",
        "max_length": "max_seq_length",
    }
    for key, out in arg_map.items():
        m = re.search(r"\b" + key + r"\s*=\s*" + _NUM, script_text)
        if m:
            cfg[out] = _parse_float(m.group(0).split("=", 1)[1])

    # output_dir
    m = re.search(r'\boutput_dir\s*=\s*["\']([^"\']+)["\']', script_text)
    if m:
        cfg["output_dir"] = m.group(1)

    # dataset path
    m = re.search(
        r'load_dataset\s*\([^)]*?\bdata_files\s*=\s*["\']([^"\']+)["\']', script_text)
    if m:
        cfg["dataset_path"] = m.group(1)
    else:
        m = re.search(r'load_dataset\s*\(\s*["\']([^"\']+)["\']', script_text)
        if m:
            cfg["dataset_path"] = m.group(1)

    cfg.setdefault("training_backend", "unsloth")
    return cfg


# ── Output parsing (SFTTrainer lines → mama IPC) ──────────────────────────────

_TRAIN_DICT_RE = re.compile(r"\{.*?\}")


def parse_trainer_line(line: str, state: dict):
    text = line.strip()
    if not text:
        return

    m = _TRAIN_DICT_RE.search(text)
    if m:
        try:
            import ast
            data = ast.literal_eval(m.group(0))
            if isinstance(data, dict) and "loss" in data:
                step = data.get("step") or state.get("last_step", 0) + 1
                state["last_step"] = int(step)
                emit({
                    "type": "metric",
                    "step": int(step),
                    "loss": data.get("loss"),
                    "learning_rate": data.get("learning_rate"),
                    "epoch": data.get("epoch"),
                })
                return
        except (ValueError, SyntaxError):
            pass

    if "out of memory" in text.lower() or "OutOfMemoryError" in text:
        emit_error("OOM", "GPU out of memory during training", [
            "Reduce per_device_train_batch_size",
            "Increase gradient_accumulation_steps",
            "Disable QLoRA (use LoRA) or lower lora_r",
            "Reduce max_seq_length / sequence_len",
        ])
        return

    emit({"type": "log", "text": text})


# ── Process tree helpers ──────────────────────────────────────────────────────


def kill_process_tree(proc):
    try:
        pgid = os.getpgid(proc.pid)
        os.killpg(pgid, signal.SIGTERM)
        try:
            proc.wait(timeout=5)
        except subprocess.TimeoutExpired:
            os.killpg(pgid, signal.SIGKILL)
    except (ProcessLookupError, PermissionError, OSError):
        try:
            proc.terminate()
        except OSError:
            pass


def watch_control_files(output_dir: str, proc: subprocess.Popen):
    pause_file = Path(output_dir) / ".pause"
    cancel_file = Path(output_dir) / ".cancel"
    paused = False
    while proc.poll() is None:
        if cancel_file.exists():
            emit_status("Cancel signal received. Stopping training...", "done")
            kill_process_tree(proc)
            return
        if pause_file.exists() and not paused:
            paused = True
            emit_status("Pause signal detected. Pausing...", "training")
            try:
                os.killpg(os.getpgid(proc.pid), signal.SIGSTOP)
            except (ProcessLookupError, PermissionError, OSError):
                pass
        elif not pause_file.exists() and paused:
            paused = False
            emit_status("Resuming training...", "training")
            try:
                os.killpg(os.getpgid(proc.pid), signal.SIGCONT)
            except (ProcessLookupError, PermissionError, OSError):
                pass
        time.sleep(1)


def ensure_unsl():
    if is_unsloth_installed():
        emit_status("Unsloth already installed", "loading")
        return True
    emit_status("Installing unsloth (this can take a few minutes)...", "loading")
    if sys.platform == "darwin":
        cmd = [sys.executable, "-m", "pip", "install", "--upgrade",
               "--force-reinstall", "--no-cache-dir",
               "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"]
    else:
        cmd = [sys.executable, "-m", "pip", "install", "--no-input",
               "--disable-pip-version-check", "unsloth"]
    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE,
                            stderr=subprocess.STDOUT, text=True, bufsize=1)
    for line in iter(proc.stdout.readline, ""):
        if line and line.strip():
            emit({"type": "install_log", "text": line.rstrip()})
    proc.wait()
    if proc.returncode != 0:
        emit_error("IMPORT", "Failed to install unsloth via pip", [
            "Check your network connection and pip index",
            "macOS requires the git install (see install steps)",
        ])
        return False
    if not is_unsloth_installed():
        emit_error("IMPORT", "unsloth installed but failed to import")
        return False
    return True


# ── Main ──────────────────────────────────────────────────────────────────────


def main():
    parser = argparse.ArgumentParser(description="Unsloth fine-tuning runner")
    parser.add_argument("--config", help="Path to mama training config JSON")
    parser.add_argument("--mode", choices=("platform-check", "gen-script",
                                            "import", "run"), default="run")
    parser.add_argument("--script", help="Unsloth script to import / run")
    parser.add_argument("--output-dir", help="Output directory for generated script")
    args = parser.parse_args()

    signal.signal(signal.SIGTERM, lambda *_: sys.exit(0))

    try:
        if args.mode == "platform-check":
            info = {"backend": "unsloth"}
            device = get_device()
            info.update({
                "device": device,
                "cuda_available": device == "cuda",
                "mps_available": device == "mps",
                "supported": device in ("cuda", "mps"),
                "unsloth_installed": is_unsloth_installed(),
                "reason": "Unsloth needs CUDA or Apple Silicon (MPS). CPU is allowed but very slow.",
            })
            emit({"type": "platform_check", **info})
            return

        if args.mode == "gen-script":
            if not args.config:
                emit_error("CONFIG", "--config is required for gen-script")
            with open(args.config, "r", encoding="utf-8") as f:
                cfg = json.load(f)
            script = render_standalone_script(cfg)
            out_dir = args.output_dir or cfg.get("output_dir") or "."
            Path(out_dir).mkdir(parents=True, exist_ok=True)
            script_path = Path(out_dir) / "train_unsloth.py"
            script_path.write_text(script, "utf-8")
            emit({"type": "unsloth_script", "path": str(script_path),
                  "script": script})
            return

        if args.mode == "import":
            if not args.script:
                emit_error("CONFIG", "--script is required for import")
            script_path = Path(args.script)
            if not script_path.exists():
                emit_error("CONFIG", f"Script not found: {args.script}")
            cfg = parse_import_config(script_path.read_text("utf-8"))
            out_dir = args.output_dir or cfg.get("output_dir") or "."
            Path(out_dir).mkdir(parents=True, exist_ok=True)
            config_path = Path(out_dir) / "training_config.json"
            config_path.write_text(json.dumps(cfg, indent=2), "utf-8")
            emit({"type": "unsloth_import", "config": cfg,
                  "path": str(config_path), "script": str(script_path)})
            return

        # ── run mode ─────────────────────────────────────────────────────
        if not args.config:
            emit_error("CONFIG", "--config is required")

        with open(args.config, "r", encoding="utf-8") as f:
            cfg = json.load(f)

        output_dir = cfg.get("output_dir", "")
        if not output_dir:
            emit_error("CONFIG", "output_dir is required in config")
        Path(output_dir).mkdir(parents=True, exist_ok=True)

        # Platform validation
        device = get_device()
        if device not in ("cuda", "mps"):
            emit_status("Warning: no CUDA/MPS GPU detected; training on CPU will be very slow.", "loading")

        if not ensure_unsl():
            return

        # Render the standalone script (same artifact the Export page makes)
        script_text = render_standalone_script(cfg)
        script_path = Path(output_dir) / "train_unsloth.py"
        script_path.write_text(script_text, "utf-8")
        emit_status(f"Unsloth script written: {script_path}", "loading")

        # Spawn it; the generated script reads the config we write next.
        config_path = Path(output_dir) / "training_config.json"
        config_path.write_text(json.dumps(cfg, indent=2), "utf-8")

        cmd = [sys.executable, str(script_path), "--config", str(config_path)]
        emit_status(f"Launching: {' '.join(cmd)}", "training")

        proc = subprocess.Popen(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1,
            start_new_session=True,
            env=dict(os.environ),
        )

        state = {"last_step": 0}
        threading.Thread(target=watch_control_files,
                         args=(output_dir, proc), daemon=True).start()

        for line in iter(proc.stdout.readline, ""):
            if line:
                parse_trainer_line(line, state)
        proc.wait()

        if proc.returncode == 0:
            emit_status("Training completed. Model saved to " + output_dir, "done")
        else:
            emit({"type": "done", "code": proc.returncode})
            sys.exit(proc.returncode)
    except SystemExit:
        raise
    except Exception as e:
        emit_error("FATAL", str(e), [], traceback_str=None)


if __name__ == "__main__":
    main()
